### ISSUE TITLE
Error on mopidy start

### ISSUE THREAD

**Issue by mbmelgo** [jaedb/spotmop#136]
This generates an error after installing spotmop and starting mopidy

ERROR    Loading spotmop failed.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/http/actor.py", line 135, in _get_app_request_handlers
    request_handlers = app['factory'](self.config, self.core)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_spotmop/__init__.py", line 86, in spotmop_client_factory
    "path": config['local-images']['image_dir']
  File "/usr/lib/python2.7/dist-packages/mopidy/config/**init**.py", line 283, in **getitem**
    item = self._data.__getitem__(key)
KeyError: u'local-images'

**Comment by choseh** [comment]
Same here,
looks like there is no config section "local-images" and thus no image_dir key. I set the path in **init**.py to something that exists, since I don't need any local album art or whatever. Maybe creating a [local-images] section with an image_dir key in mopidy.config could work, but I'll just let @jaedb fix that :)
